# Generated by Django 5.2.16 on 2026-08-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_document_document_type_document_verification_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockVerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
