# Generated by Django 5.2.16 on 2026-08-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0005_mockverificationrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockverificationrecord',
            name='identifier',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='mockverificationrecord',
            constraint=models.UniqueConstraint(fields=('document_type', 'identifier'), name='unique_mock_document_identifier'),
        ),
    ]
